<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Shaders\*.spv" LogicalName="Shaders.%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Talesmith.Rendering\Talesmith.Rendering.csproj" />
    <ProjectReference Include="..\..\src\Talesmith.Rendering.Skia\Talesmith.Rendering.Skia.csproj" />
    <ProjectReference Include="..\..\src\Talesmith.Rendering.Vulkan\Talesmith.Rendering.Vulkan.csproj" />
  </ItemGroup>
</Project>
