using System.Text;
using System.Xml.Linq;
using Talesmith.Assets;
using Talesmith.Scripting.Compiler.Analyzers;

namespace Talesmith.Scripting.Compiler;

/// <summary>Writes a <c>.csproj</c> for a project's scripts, so Rider, Visual Studio and VS Code offer IntelliSense, navigation and debugging.</summary>
/// <remarks>
/// The project compiles the same files with the same references, global usings, symbols and analyzers as <see cref="ScriptCompiler"/>, against the
/// engine assemblies by path. It ignores the build settings of folders above it, and builds into <c>.talesmith/ide/</c>, which the asset
/// database and builds skip. Regenerate it whenever the plugins or engine change; <see cref="Write"/> only touches the file when its
/// content changed, so IDEs do not reload needlessly.
/// </remarks>
public static class ScriptProjectFile
{
    /// <summary>Where IDE builds put their output, relative to the project folder.</summary>
    public const string OutputDirectory = ".talesmith/ide/";

    /// <summary>The path of the project file: <c>&lt;project&gt;/&lt;project folder name&gt;.Scripts.csproj</c>.</summary>
    public static string PathFor(ScriptCompilerOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        var directory = Path.GetFullPath(options.ProjectDirectory);
        return Path.Combine(directory, Path.GetFileName(Path.TrimEndingDirectorySeparator(directory)) + ".Scripts.csproj");
    }

    /// <summary>The project file's content for the compiler options; references outside the framework are written as hint paths.</summary>
    public static string Generate(ScriptCompilerOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        var projectDirectory = Path.GetFullPath(options.ProjectDirectory);
        var framework = ScriptReferences.Framework().ToHashSet(StringComparer.Ordinal);
        var sources = Path.GetRelativePath(projectDirectory, options.SourceRoot).Replace('\\', '/');
        var projectName = Path.GetFileName(Path.TrimEndingDirectorySeparator(projectDirectory));
        var defines = new List<string> { "TALESMITH" };
        defines.AddRange(options.Defines);

        XElement Property(string name, string value) => new(name, value);
        var project = new XElement("Project",
            new XElement("PropertyGroup",
                Property("ImportDirectoryBuildProps", "false"),
                Property("ImportDirectoryBuildTargets", "false"),
                Property("ImportDirectoryPackagesProps", "false"),
                Property("BaseIntermediateOutputPath", OutputDirectory + "obj/")),
            new XElement("Import", new XAttribute("Project", "Sdk.props"), new XAttribute("Sdk", "Microsoft.NET.Sdk")),
            new XElement("PropertyGroup",
                Property("TargetFramework", $"net{Environment.Version.Major}.{Environment.Version.Minor}"),
                Property("AssemblyName", options.AssemblyName),
                Property("RootNamespace", ScriptTemplates.NamespaceFor(projectName)),
                Property("LangVersion", "latest"),
                Property("Nullable", "enable"),
                Property("ImplicitUsings", "disable"),
                Property("EnableDefaultItems", "false"),
                Property("ManagePackageVersionsCentrally", "false"),
                Property("OutputPath", OutputDirectory + "bin/"),
                Property("AppendTargetFrameworkToOutputPath", "false"),
                Property("DefineConstants", "$(DefineConstants);" + string.Join(';', defines))),
            new XElement("ItemGroup",
                new XElement("Compile", new XAttribute("Include", $"{sources}/**/*.cs"), new XAttribute("Exclude", $"{sources}/**/bin/**;{sources}/**/obj/**;{sources}/**/.*/**"))),
            new XElement("ItemGroup", ScriptCompiler.GlobalUsings.Select(name => new XElement("Using", new XAttribute("Include", name)))),
            new XElement("ItemGroup", options.References.Concat(options.AdditionalReferences)
                .Where(path => !framework.Contains(path))
                .Distinct(StringComparer.Ordinal)
                .Select(path => new XElement("Reference", new XAttribute("Include", Path.GetFileNameWithoutExtension(path)),
                    Property("HintPath", Path.GetFullPath(path)),
                    Property("Private", "false")))),
            new XElement("ItemGroup", new XElement("Analyzer", new XAttribute("Include", typeof(GameLoopAnalyzer).Assembly.Location))),
            new XElement("Import", new XAttribute("Project", "Sdk.targets"), new XAttribute("Sdk", "Microsoft.NET.Sdk")));

        var text = new StringBuilder();
        text.Append("<!-- Generated by Talesmith for IDE support; changes are overwritten. Scripts compile in the editor, not with this project. -->\n");
        text.Append(project.ToString().ReplaceLineEndings("\n")).Append('\n');
        return text.ToString();
    }

    /// <summary>Writes the project file when its content changed; returns whether it was written.</summary>
    public static bool Write(ScriptCompilerOptions options)
    {
        var path = PathFor(options);
        var content = Generate(options);
        if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
            return false;
        AtomicFile.WriteAllText(path, content);
        return true;
    }
}
