using Talesmith.Assets;
using Talesmith.Authoring;
using Talesmith.Rendering;

namespace Talesmith.VFX;

/// <summary>Textures generated by the engine, so effects look good without any image assets.</summary>
public enum BuiltInParticleTexture
{
    /// <summary>A round blob fading smoothly to its edge.</summary>
    SoftCircle,

    /// <summary>A bright core with a wide, faint halo, for light and magic.</summary>
    Glow,

    /// <summary>A crisp, anti-aliased disc.</summary>
    Disc,

    /// <summary>A billowing, uneven puff.</summary>
    Smoke,

    /// <summary>A four-pointed twinkle.</summary>
    Sparkle,

    /// <summary>A soft streak along the X axis, for sparks and rain drawn with stretching.</summary>
    Streak,

    Square
}

/// <summary>Which particles are drawn in front within one emitter.</summary>
public enum ParticleSortMode
{
    /// <summary>No particular order; the fastest.</summary>
    None,

    /// <summary>Older particles in front, so new ones appear from behind, as with smoke.</summary>
    OldestInFront,

    /// <summary>Newer particles in front.</summary>
    YoungestInFront,

    /// <summary>Particles lower on screen in front, for top-down scenes.</summary>
    ByY
}

/// <summary>How particles are turned.</summary>
public enum ParticleAlignment
{
    /// <summary>By their own rotation.</summary>
    Rotation,

    /// <summary>Along their velocity, plus their rotation.</summary>
    Velocity,

    /// <summary>Along their velocity and stretched by their speed, for sparks, rain and streaks.</summary>
    Stretch
}

/// <summary>How particles are drawn: texture, blending, layer and order.</summary>
public sealed class ParticleRendererModule
{
    public bool Enabled = true;

    [Tooltip("The image drawn for each particle; when empty, the built-in texture is used.")]
    [AssetFilter(".png", ".jpg", ".jpeg", ".webp")]
    public AssetGuid Texture;

    [Tooltip("A named sprite of the texture; empty uses the whole image.")]
    public string? Sprite;

    [Label("Built-in texture")]
    [Tooltip("The engine-generated image drawn when no texture is set.")]
    public BuiltInParticleTexture BuiltInTexture = BuiltInParticleTexture.SoftCircle;

    [Tooltip("Alpha for normal transparency, Additive for light such as fire and magic, Multiply to darken.")]
    public BlendMode Blend = BlendMode.Alpha;

    [Tooltip("The render layer; Effects (400) draws above characters.")]
    public int Layer = RenderLayers.Effects;

    [Label("Sort order")]
    [Tooltip("Orders emitters on the same layer; higher draws in front.")]
    public float SortOrder;

    [Label("Sort by emitter Y")]
    [Tooltip("Orders emitters on the same layer by their Y position, like sprites that sort by Y.")]
    public bool SortByEmitterY;

    [Label("Particle order")]
    [Tooltip("Which particles of this emitter are drawn in front.")]
    public ParticleSortMode SortMode = ParticleSortMode.None;

    [Tooltip("How particles are turned: by rotation, along their velocity, or stretched along it.")]
    public ParticleAlignment Alignment = ParticleAlignment.Rotation;

    [Label("Stretch by speed")]
    [Tooltip("Extra length per unit of speed when stretching.")]
    [Range(0, 1, Step = 0.001)]
    public float StretchSpeedScale = 0.05f;

    [Label("Stretch length")]
    [Tooltip("The length multiplier when stretching, before speed is added.")]
    [Range(0, 10)]
    public float StretchLengthScale = 1;
}
