using Talesmith.Screenshots.Scenes;

namespace Talesmith.Screenshots.Docs;

/// <summary>The screenshots of the editor guide, in website/static/img/screenshots/guide.</summary>
internal static class GuideShots
{
    public static IReadOnlyList<DocsShot> All { get; } =
    [
        new("project-hub", new HubScene(), "The project hub listing recent projects with thumbnails of their scenes"),
        new("new-project", new HubNewProjectScene(), "The New project page of the hub with the Empty, hex adventure and platformer templates"),
        new("editor-window", new EditorWindowScene(), "The editor with a platformer scene in the viewport, the hierarchy, the inspector and the console"),
        new("hierarchy", new EditorHierarchyScene(), "The Hierarchy panel with nested groups while an entity is dragged onto another"),
        new("inspector", new EditorInspectorScene(), "The Inspector showing an entity's sprite, collider, light, particle emitter and script sections"),
        new("add-component", new EditorAddComponentScene(), "The Add component popup below the Hero, listing recently used components and then components by category"),
        new("gizmos", new EditorGizmoScene(), "Move handles on a selected sprite and light, with the light's radius gizmo"),
        new("prefab-editing", new EditorPrefabScene(), "A prefab open for editing, with a breadcrumb in the hierarchy leading back to the scene"),
        new("assets-grid", new AssetsGridScene(), "The Assets panel showing a folder of character sprites as thumbnails"),
        new("assets-list", new AssetsListScene(), "The Assets panel's list view of an audio folder with waveform thumbnails"),
        new("assets-create", new AssetsCreateMenuScene(), "The Create menu of the Assets panel"),
        new("asset-texture", new AssetTextureInspectorScene(), "A texture in the asset inspector with its preview, sprites and import settings"),
        new("asset-audio", new AssetAudioInspectorScene(), "A sound in the asset inspector with its waveform, loop markers and import settings"),
        new("asset-atlas", new AssetInspectorScene("editor-asset-atlas", "sprites/characters.tatlas"), "A sprite atlas in the asset inspector"),
        new("asset-font", new AssetInspectorScene("editor-asset-font", "fonts/Inter-Bold.ttf"), "A font in the asset inspector with a preview of its glyphs"),
        new("asset-prefab", new AssetInspectorScene("editor-asset-prefab", "prefabs/crab.tprefab"), "A prefab in the asset inspector"),
        new("sprite-editor", new SpriteEditorScene(), "The sprite editor with a sliced character sheet, a selected sprite and an animation in the frame strip"),
        new("tilemap-hex", new TileMapScene(), "A hex map in the Tile Mapping layout with the Tile Map panel's layers and palette"),
        new("tilemap-square", new TileMapSquareScene(), "A rectangular platformer level in the Tile Mapping layout"),
        new("tilemap-stroke", new TileMapStrokeScene(), "A rectangle being dragged out on a map, previewing its tiles, next to a selection"),
        new("tileset-import", new TilesetImportScene(), "The tileset import dialog slicing a tileset image into tiles"),
        new("terrain-editor", new TerrainEditorScene(), "The terrain editor with a rule's neighbor pattern and weighted outputs"),
        new("particle-editor", new ParticleEditorScene(), "The particle editor on a campfire effect with color and size curves and a live preview"),
        new("particle-presets", new ParticlePresetsScene(), "The gallery of built-in particle presets, each playing in its own preview"),
        new("lighting-panel", new LightingPanelScene(), "The Lighting panel on a night scene with torches, a lamp, the moon and shadow casters"),
        new("play-mode", new EditorPlayScene(), "Play mode with the running game in the Game panel and the app bar in the accent color"),
        new("console", new EditorConsoleScene(), "The console with messages of every severity, collapsed duplicates and the details of an error"),
        new("command-palette", new EditorPaletteScene(), "The command palette searching commands, entities and assets"),
        new("settings", new EditorSettingsScene(), "The Settings dialog on its Viewport page with the grid, snapping, entity icon and zoom settings"),
        new("project-input", new EditorInputSettingsScene(), "Project Settings on the input page, recording a new key for an action"),
        new("project-physics", new EditorPhysicsSettingsScene(), "Project Settings on the physics page with named layers and the collision matrix"),
        new("build-progress", new EditorBuildProgressScene(), "The Build dialog while it publishes the Windows player"),
        new("first-game-new-project", new TutorialHubScene(), "The New project page with the Side-scrolling platformer template chosen and Coin Run as the name"),
        new("first-game-starter", TutorialShots.Starter(), "Coin Run's starter scene with the hero selected and the coins listed in the hierarchy"),
        new("first-game-collision", TutorialShots.Collision(), "The Tile Map panel with the level's Ground layer given the Collision role"),
        new("first-game-paint", TutorialShots.Paint(), "The brush painting grass tiles across a gap in the level"),
        new("first-game-physics", TutorialShots.Physics(), "The hero with a Collider 2D and a Character Controller 2D, its collider outlined in the viewport"),
        new("first-game-script-dialog", TutorialShots.ScriptDialog(), "The Create script dialog with HeroController as the class name and the Script template chosen"),
        new("first-game-build", TutorialShots.Build(), "The Build dialog with the Linux x64 platform marked This PC and the Release profile chosen"),
        new("first-game-script", TutorialShots.Script(), "The HeroController script on the hero, with its Run Speed, Jump Speed and Gravity fields"),
        new("first-game-coins", TutorialShots.Coins(), "Five coins selected together, each with a trigger collider and the Coin script"),
        new("first-game-campfire", TutorialShots.Campfire(), "A campfire of fire particles with a flickering point light, under dusk lighting"),
        new("first-game-play", TutorialShots.Play(), "Coin Run playing in the Game panel"),
        new("tilemap-new-dialog", TileMapShots.NewMapDialog(), "The New tile map dialog with the grid choices, the hex size and the file name"),
        new("tilemap-layers", TileMapShots.Layers(), "The Tile Map panel on Lantern Grove's map, with its layers and their roles above the tileset palette"),
        new("tilemap-collision", TileMapShots.Collision(), "The Collision tool painting solid cells on a hex island, on a collision layer it added"),
        new("tilemap-select", TileMapShots.Select(), "A rectangle of hexes selected with the Select Tiles tool, its options in the tool options bar"),
        new("tilemap-objects", TileMapShots.Objects(), "An object selected with the Objects tool, its name, type and properties in the Tile Map panel"),
        new("tile-properties", TileMapShots.TileProperties(), "The Tile properties dialog on its Collision page, with a tile's collision shape"),
        new("play-paused", WorkflowShots.Paused(), "Play mode paused: the app bar's strip and the Game panel's frame in amber, the hero's live values in the inspector"),
        new("play-blocked", WorkflowShots.Blocked(), "The Cannot play yet message after pressing Play while the scripts have a compile error, and 1 script error in the status bar"),
        new("console-script-errors", new EditorScriptErrorScene(), "The console filtered to scripts, with a compile error selected showing its file and line"),
        new("history-panel", WorkflowShots.History(), "The History panel listing the steps of setting up the coins, with the current step checked"),
        new("layout-effects", WorkflowShots.EffectsLayout(), "The Effects layout: the Particles and Lighting panels in the right column above the Inspector"),
        new("project-game", WorkflowShots.ProjectGame(), "Project Settings on Isle Hopper's Game page, scrolled to the View section: fit, a 640 × 360 design size, integer scale, a 1280 × 720 overlay size, black bars and the sentence describing what a 1280 × 720 window shows"),
        new("project-loading-screen", WorkflowShots.ProjectLoadingScreen(), "Project Settings scrolled to the Loading screen section: its preview, the image, the two colors and the switch for scene changes"),
        new("settings-appearance", WorkflowShots.SettingsAppearance(), "The Settings dialog on its Appearance page with the color mode and accent colors"),
        new("settings-keyboard", WorkflowShots.SettingsKeyboard(), "The Settings dialog's Keyboard page filtered to play commands, recording a new shortcut for Play from start scene"),
        new("shortcuts-dialog", WorkflowShots.Shortcuts(), "The Keyboard shortcuts sheet grouped by category"),
        new("asset-health", AssetShots.Health(), "The Asset health dialog with a missing reference, an orphaned .meta file and the unreferenced assets"),
        new("assets-search", AssetShots.Search(), "The Assets panel searching the whole project for kind:texture"),
        new("lighting-night", EffectsShots.NightScene(), "Lantern Grove at night with Preview on, the campfire selected with the radius gizmos of its light"),
        new("scene-settings", SceneShots.SceneSettings(), "The Inspector with nothing selected, showing the scene's background, ambient light, gravity and render layers"),
        new("hierarchy-filter", SceneShots.HierarchyFilter(), "The Hierarchy filtered to the coins whose names contain 2, with their parent dimmed"),
        new("viewport-camera", SceneShots.Camera(), "The main camera selected in the viewport, its 640 × 360 frame labeled with its name, design size, scale mode and zoom"),
        new("viewport-rotate", SceneShots.Rotate(), "The Rotate tool's ring around the selected hero"),
        new("prefab-instance", SceneShots.PrefabInstance(), "A coin prefab instance with an overridden animation speed, its prefab badge and the hierarchy's modified dot"),
        new("build-report", new EditorBuildReportScene(), "The build report after exporting Hex Quest for Linux"),
    ];
}
